server:
  port: 4200
spring:
  application:
    name: "Clean Architecture Example"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
      - jpaAdapter
      - ADPAuthorization